version: '2'

services:
    php-redis-admin:
        build: .
        volumes: 
            - ./php-redis-admin:/var/www/html/php-redis-admin
            - ./docker/config.inc.php:/var/www/html/php-redis-admin/includes/config.inc.php
            - ./redis-data:/data
        ports:
            - "8080:80"
        networks:
            - public
            - backend
        depends_on:
            - redis
    redis:
        image: redis:alpine
        volumes:
            - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        networks:
            backend:
                aliases:
                - redis_admin
      

networks:
    public:
    backend:
